"use client";
import {useRef,useState} from 'react';
import {Upload,FileText,CheckCircle} from 'lucide-react';
async function extract(file:File){
const ext=file.name.split('.').pop()?.toLowerCase();
if(ext==='txt'||ext==='md')return file.text();
if(ext==='docx'){const mammoth=await import('mammoth');const result=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return result.value;}
if(ext==='pdf'){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())});const doc=await task.promise;try{if(doc.numPages>100)throw new Error('PDF는 100쪽 이하로 나누어 주세요.');const pages=[];for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n);const content=await page.getTextContent();let lastY:number|null=null;let str='';for(const item of content.items){if(!('str' in item))continue;const y=item.transform[5];if(lastY!==null&&Math.abs(y-lastY)>3)str+='\n';str+=item.str+' ';if(item.hasEOL)str+='\n';lastY=y;}pages.push(str);}return pages.join('\n\n');}finally{await task.destroy();}}
throw new Error('PDF, DOCX, TXT, MD 파일을 선택해 주세요.');}
export default function UploadDocument({onComplete}:{onComplete:()=>Promise<void>}){const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(false);
async function run(file:File){setBusy(true);setError(false);try{if(file.size>10*1024*1024)throw new Error('파일은 10MB 이하로 올려주세요.');setStatus('문서 내용을 추출하고 있습니다…');const text=await extract(file);if(text.trim().length<80)throw new Error('텍스트가 부족합니다. 스캔·이미지 PDF는 OCR 처리 후 다시 올려주세요.');if(text.length>150000)throw new Error('텍스트는 15만 자 이하로 나누어 주세요.');const bytes=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());const hash=Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,'0')).join('');setStatus('원본 파일과 초안을 저장하고 있습니다…');const form=new FormData();form.append('file',file);const upload=await fetch('/api/files',{method:'POST',body:form,credentials:'same-origin'});if(!upload.ok)throw new Error(await upload.text());const f=await upload.json() as {id:string};const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({name:file.name,text,hash,fileId:f.id})});if(!r.ok)throw new Error(await r.text());await onComplete();setStatus('완료! 지원서 보관함·이력서·포트폴리오에서 확인하세요. 동일 파일의 기존 기록은 보존됩니다.');}catch(e){setError(true);setStatus(e instanceof Error?e.message:'처리 중 오류가 발생했습니다. 다시 시도해 주세요.');}finally{setBusy(false);if(input.current)input.current.value='';}}
return <section className="auto-upload"><div><span className="pill">DOCUMENT TO CAREER</span><h2>파일 하나로, 이력서와 포트폴리오까지.</h2><p>문서를 올리면 원본을 보관하고 이력서·포트폴리오 초안을 자동 생성합니다.</p><small>PDF · DOCX · TXT · MD / 최대 10MB / 별도 AI API 사용 없음 / 스캔 PDF는 OCR 필요</small></div><button className="primary" disabled={busy} onClick={()=>input.current?.click()}><Upload size={18}/>{busy?'생성 중…':'파일 업로드 · 자동 생성'}</button><input ref={input} type="file" accept=".pdf,.docx,.txt,.md" style={{display:'none'}} disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)run(f)}}/>{status&&<p role="status" className={error?'upload-error':'upload-status'}>{status}</p>}</section>}
